### ISSUE TITLE
Project 1 Feedback

### ISSUE THREAD

**Issue by jadencarver** [raquelhosein/pointsofsales#1]
Hey Raquel,

I'm finally getting around to Project 1 Feedback, and here are my observations:

- Your HTML looks well formatted - though I'm seeing a floating `</nav>` near the bottom that shouldn't be there. (line 44)
- Your CSS looks fantastic!
- Great job commenting your JS code.
- Instead of using IDs for `#rum` `#whiskey`, etc you could have made a general `.category` class and DRY'd that code up.
- Great job building the menu from the JS object.
- There are some missing features, such as managing multiple orders, but overall it looks good!

Great Job!

**Comment by raquelhosein** [comment]
Thanks Jaden
